# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CALab/cdp_ede_local/output/exp10/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/myudiv/myudiv.xci
# IP: The module: 'myudiv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CALab/cdp_ede_local/output/exp10/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/myudiv/myudiv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myudiv'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CALab/cdp_ede_local/output/exp10/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/myudiv/myudiv.xci
# IP: The module: 'myudiv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CALab/cdp_ede_local/output/exp10/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/myudiv/myudiv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myudiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
